#!/bin/bash

# STOP_TIME="83886080ns" # 1<<12
# STOP_TIME="327840ns"   # 1<<8
# STOP_TIME="82070ns"    # 1<<7
# STOP_TIME="20640ns"    # 1<<6
# STOP_TIME="5280ns"     # 1<<5
# STOP_TIME="1360ns"     # 1<<4
# STOP_TIME="400ns"      # 1<<3
# STOP_TIME="200ns"      # 1<<2

STOP_TIME="350ns"

#########
# analyze
#########

echo "analyse ./bench/*"
ghdl -a ./bench/benchclock.vhdl
ghdl -a ./bench/benchreset.vhdl
ghdl -a --ieee=synopsys ./bench/benchrom.vhdl
ghdl -a --ieee=synopsys ./bench/benchcounter.vhdl

echo "analyse ./nco/*"
ghdl -a ./nco/fifobuf.vhdl
ghdl -a ./nco/addsync.vhdl
ghdl -a ./nco/plcnt.vhdl
ghdl -a ./nco/placc.vhdl
ghdl -a ./nco/plnco.vhdl

echo "analyse ./plpr/*"
ghdl -a ./plpr/fifostream.vhdl
ghdl -a --ieee=synopsys ./plpr/plpr.vhdl

echo "analyse ./*_bench.vhdl"
ghdl -a --ieee=synopsys ./plpr_bench.vhdl

###########
# elaborate
###########

echo "elaborate"
ghdl -e -fsynopsys plpr_bench

################
# run and export
################

echo "run"
ghdl -r -fsynopsys plpr_bench --stop-time=${STOP_TIME} --vcd=.outputs/bench.vcd
# ghdl -r -fsynopsys plpr_bench --stop-time=${STOP_TIME}

#######
# check 
#######

python3 ./bench.py

##########
# clean up
##########

rm work-obj93.cf

######
# done
######

echo "done."
